### ISSUE TITLE
Folder Structure Issue

### ISSUE THREAD

**Issue by crmiller4** [CornellLabofOrnithology/ebirdst#1]
I have recently been trying to work through the introductory vignette for working with the STEM data in 'stemhelper'. I have been having an issue with the 'stack_stem' function resulting in the following error message:

 **Error in load_config(path) : 
  *_config.RData file does not exist in the /data directory.**

​
[STEMCode.docx](https://github.com/CornellLabofOrnithology/stemhelper/files/1459160/STEMCode.docx)

I then restructured my data into:

/norcar-ERD2016-PROD-20171009-a098806d/data/
/norcar-ERD2016-PROD-20171009-a098806d/results/

Which did not fix the error. 

After restructuring the data, and adjusting my code into the following, this issue was resolved. 

**root_path <- "C:\\Users\\mta4-a\\Downloads\\norcar-ERD2016-PROD-20171009-a098806d\\"
species <- "norcar-ERD2016-PROD-20171009-a098806d"
sp_path <- paste(root_path, species, sep = "")

 load a stack of rasters with the helper function stack_stem()
abund <- stack_stem(sp_path, variable = "abundance_umean")**

**Comment by tomauer** [comment]
Made some edits to the data packaged and helped provide example code.
