### ISSUE TITLE
Use setZ to store times

### ISSUE THREAD

**Issue by mstrimas** [CornellLabofOrnithology/ebirdst#19]
Just discovered `raster` has a formal way of storing dates associated with `RasterStack`s. `setZ()` and `getZ()` get and set dates for layers. Could be a better way of handing dates than using the layer names, which requires parsing.

**Comment by mstrimas** [comment]
Example:

```
library(raster)
r <- raster(ncol=10, nrow=10)
s <- stack(lapply(1:3, function(x) setValues(r, runif(ncell(r)))))
s <- setZ(s, as.Date("2000-1-1") + 0:2)
getZ(s)
class(getZ(s))
```

**Comment by tomauer** [comment]
Seems very handy. I wish it would also write those dates into the GeoTIFF cube.
