### ISSUE TITLE
Habitat association and avoidance from PI/PD

### ISSUE THREAD

**Issue by gdicecco** [CornellLabofOrnithology/ebirdst#25]
After taking a look at the package and the non-raster data vignette, I'm wondering how you would recommend combining PI for the land cover variables with PD to measure habitat association or avoidance - I'm thinking specifically of the estimates of positive or negative relationships with different land cover types at regional or larger scales that was previously available on the eBird Status and Trends pages for certain species. What is the relation between those data products and this one? Any thoughts on how to extract that information or something similar? Thanks!

**Comment by tomauer** [comment]
The method you talked about, that was previously available on the Status and Trends pages, for habitat is currently buried in the package, but is how we would recommend using PI and PD together.

The `cake_plot` function is internal on the `dev_erd2016` branch (https://github.com/CornellLabofOrnithology/ebirdst/blob/dev_erd2016/R/ebirdst-plotting.R). You may be able to install that branch and use it with downloaded ERD2016 runs. At the very least, you should be able to modify that code to meet your needs with those runs.

Unfortunately, at this point, the computation of PDs is not going to be available for ERD2018 runs that are going up on AWS now. There's a chance we'll calculate PDs when we do our upcoming trends work, but that hasn't been confirmed. The new model class we're using right now makes calculating PDs computationally prohibitive, but we're going to try and do it for hopefully the top ~25 predictors. I'll update here when and if that happens.

**Comment by mstrimas** [comment]
`ebirdst_habitat()` can now be used to generate habitat association data and plots
