### ISSUE TITLE
date_to_st_week() throws an error when date is on boundary of two weeks

### ISSUE THREAD

**Issue by bmvandoren** [CornellLabofOrnithology/ebirdst#30]
`date_to_st_week(as.Date("2013-10-02"))`

Error in vapply(days, check_d, FUN.VALUE = integer(length = 1)) : 
  values must be length 1,
 but FUN(X[[1]]) result is length 2

The function wants to return two weeks, both 39 and 40, but should only be giving one value.

Suggest the following change in the function:

`which(x >= dv[-length(dv)] & x <= dv[-1])` -> `which(x >= dv[-length(dv)] & x < dv[-1])`

**Comment by mstrimas** [comment]
Thanks for catching that! Should now be fixed in all branches.
