### ISSUE TITLE
Installation Failed: Long Filepaths

### ISSUE THREAD

**Issue by dwhyon** [CornellLabofOrnithology/ebirdst#36]
Running the devtools install
devtools::install_github("CornellLabofOrnithology/ebirdst")

Produces the following output:

> 
> Downloading GitHub repo CornellLabofOrnithology/ebirdst@HEAD
> ✔  checking for file 'C:\...\AppData\Local\Temp\Rtmpo9tUyl\remotes25104b9c149d\CornellLabofOrnithology-ebirdst-78c51c0/DESCRIPTION' ... 
>    Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
>      over-long path
>    Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
>      over-long path
>    Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
>      over-long path
>    Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
>      over-long path
>    Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
>      over-long path
>    Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
>      over-long path
>    Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
>      over-long path
>    Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
>      over-long path
>    Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
>      over-long path
>    Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
>      over-long path
>    Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
>      over-long path
>    Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
>      over-long path
>     ERROR
>    copying to build directory failed
> Error: Failed to install 'ebirdst' from GitHub:
>   ! System command 'Rcmd.exe' failed

Swapped my home filepath info for `...` in the quote above. 

Here's my sessionInfo()

> R version 4.2.0 (2022-04-22 ucrt)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 19044)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
> [3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
> [5] LC_TIME=English_United States.utf8    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> loaded via a namespace (and not attached):
>  [1] processx_3.6.1    compiler_4.2.0    R6_2.5.1          rprojroot_2.0.3  
>  [5] cli_3.3.0         prettyunits_1.1.1 tools_4.2.0       w> 

I previously tried changing Windows behavior for "Enable Long File Paths" in the registry, but R does not seem to recognize this. I've tried changing the directory packages are installed in in both `.libpath()` settings and with the help of `with_libpaths()` but no luck so far. Originally I was getting a message specifically mentioning long file paths are an issue in Windows, but wanted to see if there was a way to resolve this.

**Comment by mstrimas** [comment]
Sorry this is causing you trouble. It's a know issue with Windows that I'm not exactly sure how to solve (https://github.com/r-lib/remotes/issues/84). Would you mind trying two things and letting me know if either of them work?

Install without building:

```
remotes::install_github("CornellLabofOrnithology/ebirdst", build = FALSE)
```

Install from a mirror with a shorter repo name:

```
remotes::install_github("ebird/ebirdst")
```

**Comment by dwhyon** [comment]
The install without building works perfect! Thanks
