### ISSUE TITLE
Clarification on product percent-population

### ISSUE THREAD

**Issue by jivelasquezt** [CornellLabofOrnithology/ebirdst#37]
Are the values of this product between 0-1 (proportion) or 0-100 (percent)? The description reads:  "percent-population: the percent of the total relative abundance within each cell. This is a derived product calculated by dividing each cell value in the relative abundance raster with the total abundance summed across all cells". However this procedure would give you proportion instead of percentage.

**Comment by tomauer** [comment]
Proportion is the correct term, 0-1, for what's there. Although, you could multiply by 100 and call it percent.

**Comment by jivelasquezt** [comment]
Thanks for the clarification and quick reply
