### ISSUE TITLE
error in load_fac_parameters

### ISSUE THREAD

**Issue by rtrepos** [CornellLabofOrnithology/ebirdst#40]
Hi,
First thank you for this work. I have started to use your dataset (version 2020) and recently it switched to a new version (2021). I tried to adapt my code and ended up with the following error :

```
  path <- ebirdst_download(species = "batgod") #use this if running the script for the first time, otherwise use next line instead
  path <- paste0(ebirdst_data_dir(),"/2021/batgod")
  
  # load relative abundance raster stack with 52 layers, one for each week
  abd_all <- ebirdst::load_raster(path,
                                  product = "abundance",
                                  period= "weekly",
                                  resolution = "lr")
  
  # load species specific mapping parameters
  pars <- ebirdst::load_fac_map_parameters(path)

```

`Erreur dans validityMethod(object) : invalid extent: ymin >= ymax`

The traceback is the following : 

```
8: stop("invalid extent: ymin >= ymax")
7: validityMethod(object)
6: isTRUE(x)
5: anyStrings(validityMethod(object))
4: validObject(e)
3: raster::extent(unlist(p$bbox_sinu))
2: raster::extent(unlist(p$bbox_sinu))
1: ebirdst::load_fac_map_parameters(path)
```

Did I misunderstood something ? Or is there an error in the new version ?
Thanks,
Ronan

**Comment by mstrimas** [comment]
This was a bug, thanks for catching it. It should be fixed now in the GitHub version, but please test and let me know.

Also, instead of `paste0(ebirdst_data_dir(),"/2021/batgod"` you can use `get_species_path("batgod")`.

**Comment by rtrepos** [comment]
Thank you for your quick answer. I confirm you that i don't have this issue anymore using the master branch of the git.
