### ISSUE TITLE
Custom projection changed for batgod between 2020 release and 2021 release 

### ISSUE THREAD

**Issue by rtrepos** [CornellLabofOrnithology/ebirdst#41]
Hello Matt, 
First of all, thank you for this work and the help you have given me.

Actually, this issue is not really an issue. It is more a question of understanding to be sure that I did not misuse your package.
I need to extract batgod data for  year 2021 and to do this I used the master commit (bf9abb70c41aa9ff1680a48d63c5e91cdf3f4c20)

Compared to 2020 dataset version the optimized CRS is different :
for 2020 I had : "+proj=eck4 +lon_0=145.782 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs"
And for 2021 I had : "+proj=eck4 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs"

The longitude was centered on Australia in 2020 (which was great for me) and is now centered on Greenwich.
I switched to the old version (centered on Australia) and it seems ok. 

But am I doing wrong ? and why has this projection changed  ? Is there any documentation on these choices.
Thanks again
Best
Ronan

**Comment by mstrimas** [comment]
Hi Ronan, for a variety of reasons the projection can change from year to year, especially for broadly distributed species like Bar-tailed Godwit. Note however that these projections are just recommendations for mapping the full range of the species. If you have a particular region you're interested in, e.g. Australia, I'd suggest defining your own projection that's tailored to your region. I'd suggest you pick a equal area projection (e.g. Eckert IV or Lambert's Azimuthal Equal Area) that's centered on your region.
