### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [CornellLabofOrnithology/ebirdst#42]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by mstrimas** [comment]
Thanks for the heads up. I just got back from vacation and will work on moving over to **terra** in the next couple weeks!

**Comment by mstrimas** [comment]
A terra-only version of ebirdst (v2.2021.0 ) is on it's way to CRAN. Thanks!
