### ISSUE TITLE
Downloading data using common name returns too many results

### ISSUE THREAD

**Issue by julieannhart** [CornellLabofOrnithology/ebirdst#43]
When I download S&T data using common name, for example Least Flycatcher, I get files for Leaden Flycatcher as well. I expect to only get data for Least Flycatcher. Other examples where this occurs are Olive-sided Flycatcher, Grasshopper Sparrow, Great Crested Flycatcher, and Yellow-throated Warbler. It seems to be 6 letter codes that are used for multiple species and only differ by a number at the end. 
 
``` r
ebirdst::ebirdst_download(
  species = "Least Flycatcher",
  tifs_only = FALSE,
  pattern = "_smooth_mr_",
  dry_run = TRUE
)
#> Downloading data package for leafly to:
#>   /Users/juliehart/Library/Application Support/org.R-project.R/R/ebirdst
#> File list:
#>   2021/leafly/config.json
#>   2021/leafly/ranges/leafly_range_smooth_mr_2021.gpkg
#>   2021/leafly2/config.json
#>   2021/leafly2/ranges/leafly2_range_smooth_mr_2021.gpkg
```

<sup>Created on 2022-12-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mstrimas** [comment]
Sorry for the slow response, I just got back from vacation. Thanks for identifying this bug, I'll try to fix it this week!

**Comment by mstrimas** [comment]
Should be fixed now in the GitHub now, will update on CRAN soon.

```
ebirdst::ebirdst_download(
+     species = "Least Flycatcher",
+     tifs_only = FALSE,
+     pattern = "_smooth_mr_",
+     dry_run = TRUE
+ )
#> Downloading data package for leafly to:
#>   /Users/mes335/data/ebirdst
#> File list:
#>   2021/leafly/ranges/leafly_range_smooth_mr_2021.gpkg
```

**Comment by julieannhart** [comment]
Awesome. Thanks! Hope South Africa was great!
